DROP TABLE IF EXISTS Prime;

CREATE TABLE Prime (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Time TIME DEFAULT NULL,
  User VARCHAR(250) NOT NULL,
  Upperlimit VARCHAR(250) NOT NULL,
  LowerLimit VARCHAR(250) NOT NULL,
  ElapsedTime VARCHAR(250) DEFAULT NULL,
  Algorithm VARCHAR(250) NOT NULL,
  NoPrimeReturned INT DEFAULT NULL
);
